IDENTITY_USER_TOPIC = "identity.user"
IDENTITY_COMPANY_PROFILE_TOPIC = "identity.company_profile"
IDENTITY_MEMBERSHIP_TOPIC = "identity.membership"

CATALOG_PRODUCT_TOPIC = "catalog.product"
CATALOG_VARIANT_TOPIC = "catalog.variant"
INVENTORY_AVAILABILITY_TOPIC = "inventory.availability"
POS_ORDER_TOPIC = "pos.order"
AUDIT_EVENTS_TOPIC = "audit_events"
NOTIFICATION_EVENTS_TOPIC = "notification_events"
SUPPORT_ACCESS_EVENTS_TOPIC = "support_access_events"
