# Generated by Django 5.2.7 on 2026-03-12 11:08

import django.db.models.deletion
import django.utils.timezone
import mainapps.profile.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('chatgpt', 'Chat GPT'), ('gemini', 'Gemini'), ('grok', 'Grok')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_sequence', models.PositiveIntegerField(default=0)),
                ('inventory_sequence', models.PositiveIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, db_index=True, editable=False, help_text='Unique company login code used for tenant-scoped authentication.', max_length=15, null=True, unique=True, verbose_name='Company Code')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Company name')),
                ('industry', models.CharField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Logistics', 'Logistics'), ('Healthcare', 'Healthcare'), ('Food & Beverage', 'Food & Beverage'), ('Technology', 'Technology'), ('Construction', 'Construction'), ('Pharmaceutical', 'Pharmaceutical'), ('Automotive', 'Automotive'), ('Other', 'Other')], help_text='Industry in which the company operates (optional)', max_length=50, null=True, verbose_name='Industry')),
                ('description', models.CharField(blank=True, help_text='Briefly describe the company', max_length=1000, null=True, verbose_name='Company description')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Founded Date')),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees')),
                ('tax_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tax ID/VAT Number')),
                ('website', models.URLField(blank=True, help_text='Company website URL (optional)', verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Profile')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Profile')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Profile')),
                ('other_link', models.URLField(blank=True, help_text='Link to external company information or profile', verbose_name='Link/Website')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Contact email address (optional)', max_length=254, null=True, verbose_name='Email')),
                ('currency', models.CharField(blank=True, max_length=23, null=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Company')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfileAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text='Country of the address', max_length=255, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, help_text='Region or state within the country', max_length=255, null=True, verbose_name='Region/State')),
                ('subregion', models.CharField(blank=True, help_text='Subregion or province within the region', max_length=255, null=True, verbose_name='Subregion/Province')),
                ('city', models.CharField(blank=True, help_text='City of the address', max_length=255, null=True, verbose_name='City')),
                ('apt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartment number')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Street number')),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True, verbose_name='Postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical latitude of the address', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical longitude of the address', max_digits=9, null=True, verbose_name='Longitude')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='profile.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='headquarters_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.companyprofileaddress'),
        ),
        migrations.CreateModel(
            name='InventoryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('policy_type', models.CharField(choices=[('expiry', 'Expiry Management'), ('quality', 'Quality Control'), ('storage', 'Storage Requirements'), ('counting', 'Inventory Counting'), ('valuation', 'Inventory Valuation'), ('other', 'Other')], default='other', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Detailed policy configuration')),
                ('applies_to_categories', models.CharField(blank=True, help_text='Comma-separated list of inventory categories this policy applies to', max_length=255, null=True)),
                ('applies_to_all', models.BooleanField(default=False, help_text='If true, applies to all inventory items')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_policies', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_policies', to='profile.companyprofile')),
            ],
            options={
                'verbose_name': 'Inventory Policy',
                'verbose_name_plural': 'Inventory Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionFillingPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Policy name')),
                ('details', models.TextField(unique=True, verbose_name='Details of the policy')),
                ('effective_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity_period', models.IntegerField(default=5, help_text='Prescription is valid before how many days')),
                ('quantitity_limit', models.IntegerField()),
                ('refills_allowed', models.IntegerField()),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='profile.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=1000)),
                ('tavily_api_key', models.CharField(max_length=1000)),
                ('special_instruction', models.TextField(blank=True)),
                ('system_instruction', models.TextField(blank=True)),
                ('assistant_instruction', models.TextField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='profile.companyprofile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='RecallPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('severity_levels', models.JSONField(default=list, help_text='List of severity levels and their descriptions')),
                ('notification_template', models.TextField(blank=True, help_text='Template for recall notifications')),
                ('contact_information', models.JSONField(default=dict, help_text='Contact information for recall management')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recall_policies', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_policies', to='profile.companyprofile')),
            ],
            options={
                'verbose_name': 'Recall Policy',
                'verbose_name_plural': 'Recall Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('strategy_type', models.CharField(choices=[('fixed', 'Fixed Quantity'), ('economic_order_quantity', 'Economic Order Quantity'), ('min_max', 'Min-Max'), ('periodic', 'Periodic Review'), ('just_in_time', 'Just-in-Time'), ('custom', 'Custom')], default='fixed', max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters specific to the strategy type')),
                ('applies_to_categories', models.CharField(blank=True, help_text='Comma-separated list of inventory categories this strategy applies to', max_length=255, null=True)),
                ('applies_to_all', models.BooleanField(default=False, help_text='If true, applies to all inventory items')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reorder_strategies', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_strategies', to='profile.companyprofile')),
            ],
            options={
                'verbose_name': 'Reorder Strategy',
                'verbose_name_plural': 'Reorder Strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolse_created', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='permit.customuserpermission')),
                ('profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='profile.companyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='company_memberships', to='permit.customuserpermission')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='profile.companyprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='profile_com_user_id_b9cac2_idx'), models.Index(fields=['profile', 'is_active'], name='profile_com_profile_2718ef_idx')],
                'unique_together': {('user', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('invitation_code', models.CharField(default=mainapps.profile.models.generate_company_invitation_code, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('invitation_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='profile.companyprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'status'], name='profile_com_email_7393b0_idx'), models.Index(fields=['profile', 'status'], name='profile_com_profile_2ab31b_idx'), models.Index(fields=['invitation_code'], name='profile_com_invitat_6dfbf6_idx'), models.Index(fields=['expires_at', 'status'], name='profile_com_expires_f3d58c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups', to='permit.customuserpermission')),
                ('profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='profile.companyprofile')),
                ('users', models.ManyToManyField(blank=True, related_name='staff_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profile', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(editable=False, help_text='User who assigned the role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='profile.companyprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='profile.staffrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
