# Generated by Django 5.2.7 on 2026-06-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_llm_and_agent_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/%y/%m/%d/', verbose_name='Company logo'),
        ),
    ]
