# Generated by Django 5.2.7 on 2026-06-29 16:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0004_alter_customuserpermission_codename'),
        ('profile', '0003_companyprofile_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grantee_email_snapshot', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('ticket_reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('permission_mode', models.CharField(max_length=64)),
                ('membership_role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('consumed', 'Consumed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_access_grants_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_access_grants_created', to=settings.AUTH_USER_MODEL)),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='support_access_grants', to='permit.customuserpermission')),
                ('grantee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_access_grants_received', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_access_grants', to='profile.companyprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_access_grants_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='profile_sup_profile_455778_idx'), models.Index(fields=['grantee_user', 'status'], name='profile_sup_grantee_448c39_idx'), models.Index(fields=['expires_at', 'status'], name='profile_sup_expires_30584f_idx')],
            },
        ),
    ]
