# Generated by Django 5.2.7 on 2026-07-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_supportaccess_request_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="subscription_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cached subscription snapshot for the workspace.",
            ),
        ),
    ]
