# Generated by Django 5.2.7 on 2026-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_companyprofile_subscription_snapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='platform',
            field=models.CharField(choices=[('intera_ims', 'Intera IMS'), ('hosperator', 'Hosperator')], db_index=True, default='intera_ims', max_length=32),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='platform',
            field=models.CharField(choices=[('intera_ims', 'Intera IMS'), ('hosperator', 'Hosperator')], db_index=True, default='intera_ims', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='staffgroup',
            unique_together={('profile', 'platform', 'name')},
        ),
    ]
