# Generated by Django 5.2.7 on 2026-08-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_staffgroup_unique_together_staffgroup_platform_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffrole',
            unique_together={('profile', 'platform', 'name')},
        ),
    ]
