# Generated by Django 5.2.7 on 2026-08-29 15:10

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0012_seed_hosperator_integration_permissions'),
        ('profile', '0008_alter_staffrole_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='staffrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='staffgroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('platform'), models.F('profile'), name='staffgroup_profile_platform_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='staffgroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('platform'), condition=models.Q(('is_system', True)), name='staffgroup_system_platform_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='staffrole',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('platform'), models.F('profile'), name='staffrole_profile_platform_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='staffrole',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('platform'), condition=models.Q(('is_system', True)), name='staffrole_system_platform_name_ci'),
        ),
    ]
