services:
  web:
    build: .
    image: ubongpr7/intera_users:latest
    container_name: user-service
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - microservice-net
    restart: unless-stopped

networks:
  microservice-net:
    external: true

