services:
  web:
    build:
      context: .
    container_name: intera-users
    env_file:
      - .env
    command: >
      sh -c "
        uv run manage.py makemigrations &&
        uv run manage.py migrate &&
        uv run manage.py runserver 0.0.0.0:7001
      "
    volumes:
      - .:/app
      - venv:/app/.venv
    ports:
      - "7001:7001"
    restart: unless-stopped
  consumer:
    build:
      context: .
    container_name: intera-users-consumer
    env_file:
      - .env
    command: >
      sh -c "
        uv run manage.py migrate &&
        uv run manage.py consume_kafka
      "
    volumes:
      - .:/app
      - venv:/app/.venv
    restart: unless-stopped
  outbox_publisher:
    build:
      context: .
    container_name: intera-users-outbox
    env_file:
      - .env
    command: >
      sh -c "
        uv run manage.py migrate &&
        uv run manage.py publish_outbox_events
      "
    volumes:
      - .:/app
      - venv:/app/.venv
    restart: unless-stopped

volumes:
  venv:
