# Generated by Django 5.2.7 on 2026-03-12 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaConsumedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('consumer_group', models.CharField(max_length=255)),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('event_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_service', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('dead_lettered', 'Dead Lettered')], db_index=True, default='processed', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['consumer_group', 'processed_at'], name='kafka_relia_consume_64b163_idx'), models.Index(fields=['topic', 'status'], name='kafka_relia_topic_e4a0a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_id', 'consumer_group'), name='inventory_kafka_consumed_event_unique')],
            },
        ),
        migrations.CreateModel(
            name='KafkaDeadLetterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('dead_letter_topic', models.CharField(blank=True, default='', max_length=255)),
                ('consumer_group', models.CharField(db_index=True, max_length=255)),
                ('event_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_service', models.CharField(blank=True, default='', max_length=120)),
                ('message_json', models.JSONField(default=dict)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('replayed', 'Replayed')], db_index=True, default='pending', max_length=20)),
                ('failed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['consumer_group', 'status'], name='kafka_relia_consume_db82f8_idx'), models.Index(fields=['topic', 'failed_at'], name='kafka_relia_topic_c5afba_idx')],
            },
        ),
        migrations.CreateModel(
            name='KafkaOutboxEvent',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('event_key', models.CharField(blank=True, default='', max_length=255)),
                ('source_service', models.CharField(db_index=True, max_length=120)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('message_json', models.JSONField(default=dict)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('publish_attempts', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='kafka_relia_status_052744_idx'), models.Index(fields=['topic', 'created_at'], name='kafka_relia_topic_3e6a28_idx')],
            },
        ),
    ]
