# Generated by Django 5.2.2 on 2025-06-08 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Logistics', 'Logistics'), ('Healthcare', 'Healthcare'), ('Food & Beverage', 'Food & Beverage'), ('Technology', 'Technology'), ('Construction', 'Construction'), ('Pharmaceutical', 'Pharmaceutical'), ('Automotive', 'Automotive'), ('Other', 'Other')], help_text='Industry in which the company operates (optional)', max_length=50, null=True, verbose_name='Industry'),
        ),
        migrations.CreateModel(
            name='InventoryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('policy_type', models.CharField(choices=[('expiry', 'Expiry Management'), ('quality', 'Quality Control'), ('storage', 'Storage Requirements'), ('counting', 'Inventory Counting'), ('valuation', 'Inventory Valuation'), ('other', 'Other')], default='other', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Detailed policy configuration')),
                ('applies_to_categories', models.CharField(blank=True, help_text='Comma-separated list of inventory categories this policy applies to', max_length=255, null=True)),
                ('applies_to_all', models.BooleanField(default=False, help_text='If true, applies to all inventory items')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_policies', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_policies', to='management.companyprofile')),
            ],
            options={
                'verbose_name': 'Inventory Policy',
                'verbose_name_plural': 'Inventory Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecallPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('severity_levels', models.JSONField(default=list, help_text='List of severity levels and their descriptions')),
                ('notification_template', models.TextField(blank=True, help_text='Template for recall notifications')),
                ('contact_information', models.JSONField(default=dict, help_text='Contact information for recall management')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recall_policies', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_policies', to='management.companyprofile')),
            ],
            options={
                'verbose_name': 'Recall Policy',
                'verbose_name_plural': 'Recall Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('strategy_type', models.CharField(choices=[('fixed', 'Fixed Quantity'), ('economic_order_quantity', 'Economic Order Quantity'), ('min_max', 'Min-Max'), ('periodic', 'Periodic Review'), ('just_in_time', 'Just-in-Time'), ('custom', 'Custom')], default='fixed', max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters specific to the strategy type')),
                ('applies_to_categories', models.CharField(blank=True, help_text='Comma-separated list of inventory categories this strategy applies to', max_length=255, null=True)),
                ('applies_to_all', models.BooleanField(default=False, help_text='If true, applies to all inventory items')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reorder_strategies', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_strategies', to='management.companyprofile')),
            ],
            options={
                'verbose_name': 'Reorder Strategy',
                'verbose_name_plural': 'Reorder Strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
