# Generated by Django 5.2.4 on 2025-07-26 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('chatgpt', 'Chat GPT'), ('gemini', 'Gemini'), ('grok', 'Grok')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=1000)),
                ('tavily_api_key', models.CharField(max_length=1000)),
                ('special_instruction', models.TextField(blank=True)),
                ('system_instruction', models.TextField(blank=True)),
                ('assistant_instruction', models.TextField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='management.companyprofile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.modelversion')),
            ],
        ),
    ]
