# Generated by Django 5.2.2 on 2025-06-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_companyprofile_industry_inventorypolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Company name'),
        ),
    ]
