# Generated by Django 5.2.2 on 2025-06-28 22:31

import django.db.models.deletion
import mainapps.common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text='Country of the address', max_length=255, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, help_text='Region or state within the country', max_length=255, null=True, verbose_name='Region/State')),
                ('subregion', models.CharField(blank=True, help_text='Subregion or province within the region', max_length=255, null=True, verbose_name='Subregion/Province')),
                ('city', models.CharField(blank=True, help_text='City of the address', max_length=255, null=True, verbose_name='City')),
                ('apt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartment number')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Street number')),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True, verbose_name='Postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical latitude of the address', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical longitude of the address', max_digits=9, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=mainapps.common.models.attachment_upload_path)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOC', 'Document'), ('OTHER', 'Other')], max_length=20)),
                ('purpose', models.CharField(choices=[('MAIN_IMAGE', 'Main Product Image'), ('GALLERY', 'Gallery Image'), ('MANUAL', 'Product Manual'), ('SPEC', 'Specification Sheet')], default='GALLERY', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-is_primary', 'uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_atta_content_060193_idx')],
            },
        ),
    ]
