# Generated by Django 5.2.2 on 2025-06-06 17:49

import django.db.models.deletion
import mainapps.common.models
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=mainapps.common.models.attachment_upload_path)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOC', 'Document'), ('OTHER', 'Other')], max_length=20)),
                ('purpose', models.CharField(choices=[('MAIN_IMAGE', 'Main Product Image'), ('GALLERY', 'Gallery Image'), ('MANUAL', 'Product Manual'), ('SPEC', 'Specification Sheet')], default='GALLERY', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-is_primary', 'uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_atta_content_060193_idx')],
            },
        ),
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It must be unique', max_length=200, verbose_name='Type')),
                ('which_model', models.CharField(choices=[('inventory', 'Inventory'), ('stock_item', 'Stock item'), ('company', 'Company'), ('policy', 'Policy'), ('industry', 'Industry')], max_length=30)),
                ('slug', models.SlugField(editable=False, max_length=230)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='common.typeof')),
            ],
            options={
                'verbose_name_plural': 'Types of Instances',
                'constraints': [models.UniqueConstraint(fields=('name', 'which_model'), name='unique_type_name_which_model')],
            },
        ),
    ]
