# Generated by Django 5.2.7 on 2026-03-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviated_name', models.CharField(max_length=20)),
                ('dimension_type', models.CharField(choices=[('MASS', 'Mass'), ('VOLUME', 'Volume'), ('LENGTH', 'Length'), ('PIECE', 'Piece'), ('TIME', 'Time'), ('CUSTOM', 'Custom')], max_length=20)),
                ('conversion_factor', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='common.unit')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['dimension_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('dimension_type', 'name'), name='common_unit_dimension_name_unique')],
            },
        ),
    ]
