# Generated by Django 5.2.2 on 2025-06-24 11:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_type', models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('length', 'Length'), ('piece', 'Piece'), ('time', 'Time'), ('custom', 'Custom')], default='custom', help_text='Type of measurement this unit belongs to', max_length=50, verbose_name='Dimension Category')),
                ('name', models.CharField(help_text='Full name of the unit (e.g., Kilogram)', max_length=255, verbose_name='Unit Name')),
                ('abbreviated_name', models.CharField(help_text='Standard short form (e.g., kg, L, m)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_abbreviation', message='Abbreviation can only contain letters', regex='^[A-Za-z]+$')], verbose_name='Abbreviation')),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=1.0, help_text='Conversion factor to base unit', max_digits=30)),
                ('base_unit', models.ForeignKey(blank=True, help_text='Reference to base unit for conversions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.unit', verbose_name='Base Unit')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['dimension_type', 'name'], name='common_unit_dimensi_534886_idx'), models.Index(fields=['abbreviated_name'], name='common_unit_abbrevi_187618_idx')],
                'constraints': [models.UniqueConstraint(fields=('dimension_type', 'name'), name='unique_unit_per_dimension'), models.UniqueConstraint(fields=('abbreviated_name', 'dimension_type'), name='unique_abbreviation_per_dimension')],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.attribute')),
            ],
            options={
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
