# Generated by Django 5.2.7 on 2026-08-22 16:25

import django.db.models.deletion
import mainapps.accounts.models
import secrets
import string
from django.conf import settings
from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    alphabet = string.ascii_uppercase + string.digits
    used_codes = set(
        User.objects.exclude(referral_code__isnull=True)
        .exclude(referral_code='')
        .values_list('referral_code', flat=True)
    )
    for user in User.objects.filter(referral_code__isnull=True).iterator():
        code = ''.join(secrets.choice(alphabet) for _ in range(12))
        while code in used_codes:
            code = ''.join(secrets.choice(alphabet) for _ in range(12))
        User.objects.filter(pk=user.pk).update(referral_code=code)
        used_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_legalconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(db_index=True, default=mainapps.accounts.models.generate_referral_code, editable=False, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=5, default='0.05000', max_digits=6)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_reference', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('profile_id', models.CharField(blank=True, max_length=255)),
                ('plan_slug', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_payment_payouts', to=settings.AUTH_USER_MODEL)),
                ('referrer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['referrer_user', 'status'], name='accounts_re_referre_b77cb5_idx'), models.Index(fields=['referred_user'], name='accounts_re_referre_a77015_idx')],
            },
        ),
    ]
