# Generated by Django 5.2.7 on 2026-05-24 20:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('profile', '0002_llm_and_agent_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceToolConnection',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('connection_scope', models.CharField(choices=[('workspace', 'Workspace'), ('user', 'User')], default='workspace', max_length=20)),
                ('auth_type', models.CharField(blank=True, max_length=50)),
                ('server_url_override', models.CharField(blank=True, max_length=500)),
                ('credential_payload_encrypted', models.TextField(blank=True)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('resource_owner_id', models.CharField(blank=True, max_length=255)),
                ('resource_label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('expired', 'Expired'), ('error', 'Error'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tool_connections', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tool_connections', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_connections', to='profile.companyprofile')),
                ('tool_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_connections', to='agents.toolserver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tool_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'slug'), name='agents_unique_workspace_tool_connection_slug')],
            },
        ),
    ]
