# Generated by Django 5.2.2 on 2025-06-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0002_alter_customuserpermission_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissioncategory',
            name='service',
            field=models.CharField(choices=[('accommodation', 'Accommodation'), ('dining', 'Food and dining'), ('experience', 'Experience and Evemts'), ('shopping', 'Shopping'), ('services', 'Services'), ('travel', 'Travel')], default='accommodation', max_length=255),
        ),
    ]
