# Generated by Django 5.2.7 on 2026-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0006_seed_audit_trail_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuserpermission',
            options={'ordering': ['platform', 'category', 'codename']},
        ),
        migrations.AlterModelOptions(
            name='permissioncategory',
            options={'ordering': ['platform', 'name'], 'verbose_name_plural': 'Permission Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='customuserpermission',
            name='unique_permission_per_category',
        ),
        migrations.RemoveIndex(
            model_name='customuserpermission',
            name='permit_cust_codenam_3d728b_idx',
        ),
        migrations.AddField(
            model_name='customuserpermission',
            name='platform',
            field=models.CharField(choices=[('intera_ims', 'Intera IMS'), ('hosperator', 'Hosperator')], db_index=True, default='intera_ims', help_text='Product platform that owns this permission.', max_length=32),
        ),
        migrations.AddField(
            model_name='permissioncategory',
            name='platform',
            field=models.CharField(choices=[('intera_ims', 'Intera IMS'), ('hosperator', 'Hosperator')], db_index=True, default='intera_ims', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuserpermission',
            name='codename',
            field=models.CharField(help_text='Technical permission identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='permissioncategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='customuserpermission',
            index=models.Index(fields=['platform', 'codename'], name='permit_cust_platfor_c73046_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuserpermission',
            constraint=models.UniqueConstraint(fields=('platform', 'codename'), name='unique_permission_codename_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='permissioncategory',
            constraint=models.UniqueConstraint(fields=('platform', 'name'), name='unique_permission_category_per_platform'),
        ),
    ]
